//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetOwnerInfo
    {
        public string Name { get; set; }
        public string MachineName { get; set; }
        public string MachineType { get; set; }
        public string City { get; set; }
        public string Id { get; set; }
    }
}
