//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine_Data
    {
        public int MachineID { get; set; }
        public string Machine_Name { get; set; }
        public string Production { get; set; }
        public string MachineHours { get; set; }
        public string Productivity { get; set; }
        public string FuelConsumed { get; set; }
        public string IdleTime { get; set; }
        public string Distance { get; set; }
        public string NumberofCycles { get; set; }
        public string Tons { get; set; }
        public string Machine { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CustomerID { get; set; }
        public string ImagePath { get; set; }
    }
}
